# Generated by Django 3.1.4 on 2020-12-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100)),
                ('is_complete', models.BooleanField(default=False)),
                ('count_js', models.IntegerField()),
                ('count_image', models.IntegerField()),
            ],
        ),
    ]
