# Generated by Django 3.1.4 on 2021-01-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='count_css',
            field=models.IntegerField(default=0),
        ),
    ]
